name: Build and test
on:
  push:
  pull_request:
    branches:
    - 'main'
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build telescope
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: ğŸ§± Install build dependencies
      run: |
        wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list http://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
        sudo apt update && sudo apt install --upgrade cmake
        sudo apt install --upgrade libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-net-dev
        sudo apt install --upgrade vulkan-sdk
        sudo apt install --upgrade libbullet-dev libglm-dev shaderc
    - name: ğŸ¦ Build
      run: |
        cmake .
        make clean
        make
    - name: Unit tests
      run: echo TODO
    # Only upload the build and use it in the subsequent job if this is a PR, push to _Main_ or a dispatch
    - name: ğŸ†™ Upload compiled source
      if: >- 
        ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' ||
        (github.event_name == 'push' && github.event.ref == 'refs/heads/main') }}
      uses: actions/upload-artifact@v3
      with:
        name: libtelescope-pretest
        path: lib/libtelescope.so
        if-no-files-found: error
  test:
    name: Test the build
    needs: [build]
    if: >- 
      ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && github.event.ref == 'refs/heads/main') }}
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: ğŸ†’ Download dists
      uses: actions/download-artifact@v3
      with:
        name: libtelescope-pretest
        path: lib
    - name: Integration tests
      run: echo TODO
