name: Build and Test
on:
  push:
  pull_request:
    branches:
    - 'main'
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build Telescope ğŸ”­
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: ğŸ§± Install build dependencies
      run: |
        wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list http://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
        sudo apt update && sudo apt install --upgrade cmake
        sudo apt install --upgrade libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-net-dev 
        sudo apt install libglm-dev libvulkan-dev
        sudo apt install libbox2d
    - name: ğŸ¦ Build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=..
        make clean && make install
    - name: ğŸ§ª Unit tests
      run: echo noop #cd build && make test ARGS="-N" && make test ARGS="-V"
    # Only upload the build if this is a push to _Main_ or a dispatch (PRs shouldn't need this, they only need the above test)
    - name: ğŸ†™ Upload compiled source
      if: ${{ (github.event_name == 'push' && github.event.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' }}
      uses: actions/upload-artifact@v3
      with:
        name: libtelescope-pretest
        path: lib/libtelescope.so
        if-no-files-found: error
